
services:
  zpush:
    build:
      context: .
    image: ${ZPUSH_IMAGE:-local/zpush:latest}
    ports:
      - "127.0.0.1:${ZPUSH_HTTP_PORT:-9073}:8080"
    environment:
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
      - PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-50M}
      - PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-50M}
      - PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-3600}
      - PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME:-3600}
      - NGINX_CLIENT_MAX_BODY_SIZE=${NGINX_CLIENT_MAX_BODY_SIZE:-50m}
    volumes:
      - ./zpush/config:/data/config
      - ./zpush/state:/data/state
      - ./zpush/log:/data/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8080/healthz || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3

